set gfn=DejaVu\ Sans\ Mono:h16
" set gfn=Menlo_Regular:h16
set guioptions-=T
set guioptions-=l
set guioptions-=L
set guioptions-=r
set guioptions-=R
set guioptions+=c
set guioptions-=e
" set lines=50
" set columns=100
